events { }
# the event section determines how the server handles the connections behind the scenes, this is usually left empty.

http {
    # server is a virtual server 
    server {
        listen 80; #this is the standard port for the system, whenever user access the web it uses port 80
        server_name beta.cirrostrats.us; #this is the domain name that the server will respond and have accesss to, if other domains are not mentioned then they wlll not be able to access the server


        # Proxy for frontend service
        location / {
            proxy_pass http://frontend:5173;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        #this is the port for frontend part of web, whenever user goes to the web it access the port 5173

        # Proxy for backend service
        location /api {
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass http://backend:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
     
     #this is the port for backend part of web, wehenever user searches something on the web it access this port 8000 

    # we have the default port 80 here because if there is no port 80 then user will have to specify the port in the url 
    # for example test.cirrostrats.us/5173 or test.cirrostrats.us/8000 which is not user friendly
    # with the port 80 user can just enter the web of url and access both frontend and backend without specifying the port 

}
